// Copyright 2023 Danny Nguyen (@nooges)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_layers { _BASE, _LOWER, _RAISE, _ADJUST, _FUNCTION };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_BASE] = LAYOUT(
        // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
           QK_GESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                               KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TAB,   KC_B,    KC_L,    KC_D,    KC_C,    KC_V,                               KC_J,    KC_Y,    KC_O,    KC_U,    KC_SCLN, KC_BSPC,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_LCTL,  KC_N,    KC_R,    KC_T,    KC_S,    KC_G,                               KC_P,    KC_H,    KC_A,    KC_E,    KC_I,    KC_ENT,
        // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_LSFT,  KC_X,    KC_Q,    KC_M,    KC_W,    KC_Z,    MO(3),           MO(4),   KC_K,    KC_F,    KC_QUOT, KC_COMM, KC_DOT,  KC_RSFT,
        // └────────┴────────┴────────┴───┬────┴───┬────┴───┬────┴───┬────┘        └───┬────┴───┬────┴───┬────┴───┬────┴────────┴────────┴────────┘
                                           KC_LGUI, MO(1),   KC_SPC,                       KC_LSFT, MO(2),   KC_RALT
        // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),

    [_LOWER] = LAYOUT(
        // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
           LSFT(KC_GRV),LSFT(KC_1),LSFT(KC_2),LSFT(KC_3),LSFT(KC_4),LSFT(KC_5),             LSFT(KC_6),LSFT(KC_7),LSFT(KC_8),LSFT(KC_9),LSFT(KC_0),KC_BSLS,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_GRV,   KC_TAB,  LCTL(KC_C),KC_LBRC, KC_RBRC, LSFT(KC_GRV),                    KC_TRNS,  KC_P7,   KC_P8,   KC_P9,   KC_DEL,  KC_BSPC,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_DEL,   OSM(MOD_LSFT),OSM(MOD_LCTL),OSM(MOD_LALT),OSM(MOD_LGUI),KC_MINS,       KC_LEFT,  KC_DOWN, KC_UP,   KC_RGHT, KC_ENT,  LSFT(KC_BSLS),
        // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_MOD,  KC_TRNS, OSM(MOD_LCTL|MOD_LSFT),RCS(KC_C),RCS(KC_V),LSFT(KC_LBRC),LSFT(KC_LBRC),LSFT(KC_RBRC),KC_P0,KC_P1,KC_P2,KC_P3,KC_NO, KC_RSFT,
        // └────────┴────────┴────────┴───┬────┴───┬────┴───┬────┴───┬────┘        └───┬────┴───┬────┴───┬────┴───┬────┴────────┴────────┴────────┘
                                           KC_TRNS, KC_TRNS, KC_DEL,                      KC_ENT,  OSM(MOD_HYPR), KC_P0
        // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),

    [_RAISE] = LAYOUT(
        // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_F12,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                              KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  QK_BOOT,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_TOG,  KC_GRV,  LSFT(KC_COMM),LSFT(KC_DOT),KC_MINS,LSFT(KC_BSLS),             LSFT(KC_3),LSFT(KC_LBRC),LSFT(KC_RBRC),LSFT(KC_4),KC_QUOT,KC_BSPC,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_MOD,  LSFT(KC_1),LSFT(KC_8),KC_SLSH,KC_EQL,LSFT(KC_7),                        LSFT(KC_6),LSFT(KC_9),LSFT(KC_0),LSFT(KC_MINS),KC_SCLN,KC_TRNS,
        // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_MUTE,  LSFT(KC_GRV),LSFT(KC_EQL),KC_LBRC,KC_RBRC,LSFT(KC_5),LSFT(KC_9),KC_TRNS,LSFT(KC_2),LSFT(KC_SCLN),KC_COMM,KC_DOT,LSFT(KC_SLSH),RGB_HUD,
        // └────────┴────────┴────────┴───┬────┴───┬────┴───┬────┴───┬────┘        └───┬────┴───┬────┴───┬────┴───┬────┴────────┴────────┴────────┘
                                           KC_VOLD, KC_VOLU, OSM(MOD_HYPR),                 KC_TRNS, KC_TRNS, KC_TRNS
        // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),

    [_ADJUST] = LAYOUT(
        // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                               KC_Y,    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           QK_CLEAR_EEPROM,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,        KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,QK_CLEAR_EEPROM,
        // └────────┴────────┴────────┴───┬────┴───┬────┴───┬────┴───┬────┘        └───┬────┴───┬────┴───┬────┴───┬────┴────────┴────────┴────────┘
                                           KC_TRNS, KC_TRNS, KC_TRNS,                      KC_TRNS, KC_TRNS, KC_TRNS
        // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),

    [_FUNCTION] = LAYOUT(
        // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_TILD,  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                            KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSLS,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO,    KC_VOLU, KC_MPRV, KC_MPLY, KC_MNXT, KC_HOME,                            KC_NO,   KC_P7,   KC_P8,   KC_P9,   KC_NO,   KC_NO,
        // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO,    KC_VOLD, KC_NO,   KC_NO,   KC_NO,   KC_END,                             KC_NO,   KC_P4,   KC_P5,   KC_P6,   KC_NO,   KC_NO,
        // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO,    KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,           KC_TRNS, KC_P0,   KC_P1,   KC_P2,   KC_P3,   KC_NO,   KC_NO,
        // └────────┴────────┴────────┴───┬────┴───┬────┴───┬────┴───┬────┘        └───┬────┴───┬────┴───┬────┴───┬────┴────────┴────────┴────────┘
                                           KC_NO,   KC_NO,   KC_NO,                         KC_NO,   KC_NO,   KC_NO
        // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    )
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
